agent:
  tasks:
    - name: system
      repository:
        url: /Users/gilles/.plakar
      
      backup:
        path: /private/etc
        interval: 5s
        retention: 45s
        check: true

      check:
        - interval: 10s
          path: /private/etc/apache2
          latest: true
          since: 30s
