agent:
  tasks:
    - name: Backup Plakar source code
      repository: /var/backups
      #repository: /Users/niluje/dev/plakar/plakar/toto
      #repository: /Users/niluje/.plakar

      backup:
        path: /Users/niluje/dev/plakar/plakar
        interval: '20s'
        check: true
        tags:
          - backup
          - source

      #check:
      #  - interval: 1s
      #    path: /
      #    latest: true