agent:
  tasks:

    - name: system
      repository:
        url: /Users/gilles/.plakar
      #backup:
      #  - path: /private/etc
      #    interval: 5s
      #    check: true
      #    retention: 30s
      #check:
      #  - path: /
      #    interval: 30s

      restore:
        - path: /
          target: /tmp/foobar
          interval: 30s
