agent:
  tasks:
    - name: system
      repository:
        url: "@foobar"
      
      backup:
        path: /private/etc
        interval: 5s
        retention: 60s
        #check: true

      check:
        - interval: 10s
          path: /
          latest: true

      #sync:
      #  - interval: 10s
      #    direction: with
      #    peer: /tmp/foobar
