agent:
  tasks:

    - name: system
      repository:
        url: /Users/gilles/.plakar
      backup:
        - path: /private/etc
          interval: 5s
          retention: 30s
      check:
        - path: /
          interval: 1m

    - name: gilles
      repository:
        url: /Users/gilles/.plakar
      backup:
        - path: /Users/gilles/Wip/github.com/PlakarKorp/plakar
          interval: 5s
          retention: 60s
      check:
        - path: /
          interval: 1m
