agent:
    tasks:
    - name: system
      repository:
        url: /Users/gilles/.plakar
      backup:
        - description: daily-backups /etc
          path: /etc
          interval: 1m
          retention: 48h
        - description: daily-backups /private/etc
          path: /private/etc
          interval: 1m
          retention: 48h
      check:
        - description: daily-check /etc
          path: /etc
          interval: 1m
        - description: daily-check /private/etc
          path: /private/etc
          interval: 1m
