services:
  nginx:
    image: nginx:latest
    ports:
      - "80"
    volumes:
      - snapshot:/data:ro
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: default_conf
        target: /etc/nginx/conf.d/default.conf

configs:
  nginx_conf:
    content: |
      user root;
      worker_processes auto;
      error_log /var/log/nginx/error.log notice;
      pid /var/run/nginx.pid;

      events {
        worker_connections  1024;
      }
      http {
          include /etc/nginx/mime.types;
          default_type application/octet-stream;
          log_format  main '$$remote_addr - $$remote_user [$$time_local] "$$request" '
                           '$$status $$body_bytes_sent "$$http_referer" '
                           '"$$http_user_agent" "$$http_x_forwarded_for"';
          access_log /var/log/nginx/access.log  main;
          sendfile on;
          keepalive_timeout 65;
          include /etc/nginx/conf.d/*.conf;
      }

  default_conf:
    content: |
      server {
        listen 80;
        location / {
          root /data;
          autoindex on;
          index index.html;
        }
      }
