services:
  nginx:
    image: nginx:latest
    ports:
      - "80"
    volumes:
      - snapshot:/data:ro
    entrypoint: >
      sh -c "sed -i -e 's/user.*nginx;/user root;/' /etc/nginx/nginx.conf; printf 'server {listen 80; location / { root /data; autoindex on; index index.html; }}' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
