# services:
#   app:
#     volumes:
#       - snapshot:/data
#     ports:
#       - "80"
#     image: "nginx"
# # XXX: add autoindex to display files

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - snapshot:/data:ro
    entrypoint: >
      sh -c "printf 'server {listen 80; location / { root /data; autoindex on; index index.html; }}' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
