services:
  db:
    image: postgres
    volumes:
      - snapshot:/data
    environment:
      POSTGRES_PASSWORD: plakar
    working_dir: /data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      retries: 10

  init:
    image: postgres
    volumes:
      - snapshot:/data
    environment:
      PGPASSWORD: plakar
    depends_on:
      db:
        condition: service_healthy
    entrypoint: >
      bash -c "
        createdb -h db -U postgres plakar &&
        for f in /data/*.sql; do
          psql -h db -U postgres -f \"$$f\" plakar;
        done
      "
