name: Go on windows

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10
    permissions:
      contents: read
    strategy:
      matrix:
        go: [ '1.24.0' ]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v .

    # - name: Test
    #   run: go test -v ./...
